### PR TITLE
Fix bookworm image Docker copy issue

### PR DESCRIPTION
**Pull request by pacoxu**
https://github.com/ben-z/actions-comment-on-issue/pull/3#issuecomment-1591625362

### CODE REVIEW

**Comment by yosifkit** [comment]
> node:slim has no `/bin/sh`

That is incorrect. The problem comes from `COPY . .` into the root of the image. The now `bookworm`-based image uses merged usr and so `/lib` is a symlink. When `docker` does the copy, it sees that lib is not a folder and overwrites it with the copied directory, breaking basically all dynamic binaries in Debian. The fix is probably to set a `WORKDIR`.

**Comment by pacoxu** [comment]
@yosifkit thanks.
I tested it and it works fine.

**Comment by marcelklehr** [comment]
@ben-z any update on this?

**Comment by pacoxu** [comment]
> @ben-z any update on this?

I built one based on this temporarily. We use it in kubeadm. https://github.com/kubernetes/kubeadm/blob/main/.github/workflows/support-command.yaml#L23

**Comment by ben-z** [comment]
Whoa thanks for the contribution. I will merge this.

**Comment by ben-z** [comment]
Released as https://github.com/ben-z/actions-comment-on-issue/releases/tag/1.0.3

**Pull request merged**
